### ISSUE TITLE
When on_click on the rx.button() of rx. tooltip(), the tooltip cannot work

### ISSUE THREAD

**Issue by NACXA0** [reflex-dev/reflex#4232] opened 2024-10-24 03:22 UTC
**Describe the bug**
When on_click on the rx.button() of rx. tooltip(), the tooltip cannot work…
Example:

**To Reproduce**
`rx.tooltip(
rx.button(‘test_tooltip’, on_click=rx.toast.success(‘test’)),
content=‘message’
)`

**However, it is possible to do so**
`rx.tooltip(
rx.box(rx.button(‘test_tooltip’, on_click=rx.toast.success(‘test’))),
content=‘message’
)`

[thanks tomg](https://forum.reflex.dev/t/when-on-click-on-the-rx-button-of-rx-tooltip-the-tooltip-cannot-work/473/2?u=nacxa)

**Screenshots**
haven't on_click:
![normal](https://github.com/user-attachments/assets/7169c97c-1c58-4363-b340-9ad335c3275f)
![normal_code](https://github.com/user-attachments/assets/6014076e-1317-4f2a-b534-e3d1dabe6b27)

all on_click：
![have_page](https://github.com/user-attachments/assets/07d60629-3200-4ecc-bfc5-705c9b634ef3)
![have_code](https://github.com/user-attachments/assets/476b5c47-c3a7-4019-b8af-c007fd8f50ba)

add rx.box()：
![have_box_page](https://github.com/user-attachments/assets/ab26dcc0-7de6-4242-9ccb-c7bf2a83e593)
![have_box_code](https://github.com/user-attachments/assets/a21edc29-149a-4394-a97b-fe8a0c131e11)

**Specifics:**
 - Python Version:3.12
 - Reflex Version:0.6.3
 - OS: Windows
 - Browser:edge

**Comment by masenf** [comment] 2024-10-24 17:07
dupe of #3278

**Closed by masenf** 2024-10-24 17:07 UTC
Labels: bug
