### ISSUE TITLE
Unhandled Runtime Error

### ISSUE THREAD

**Issue by PlutoniaX** [reflex-dev/reflex#914] opened 2023-04-30 11:45 UTC
**Describe the bug**
When launching pc run, I get this error "Unhandled Runtime Error - TypeError: Cannot read properties of undefined (reading '_bn')

**To Reproduce**
MacOS intel BigSur (also tried on Macbook M1 Latest MacOS)
python 3.11.1
node v14.17.6
pc init 
pc run

**Expected behavior**
See screenshot

**Screenshots**
See screenshot

** Specifics (please complete the following information):**
 - Python Version:  3.11.1
 - Pynecone Version: v14.17.6
 - OS: 0.1.27
 - Browser (Optional): chrome
 
**Additional context**
![pynecone-error](https://user-images.githubusercontent.com/66722845/235351227-8f1fbe4c-9538-4d72-8bbb-64b64b0f2bc1.png)

**Comment by Alek99** [comment] 2023-05-01 05:40
Ok thanks for making an issue we will try and recreate on our end this doesn't seem to be a valid version of Pynecone `v14.17.6` are you using the latest 0.1.27 release?

**Comment by PlutoniaX** [comment] 2023-05-01 11:57
Yes sorry I am using 0.1.27. I pasted in the wrong value. 

> Ok thanks for making an issue we will try and recreate on our end this doesn't seem to be a valid version of Pynecone `v14.17.6` are you using the latest 0.1.27 release?

**Comment by ElijahAhianyo** [comment] 2023-05-01 12:08
@PlutoniaX  I'm not able to reproduce this error, did this happen after a new pynecone install or an upgrade from a previous version? Can you also share your code as well as node version?

**Comment by PlutoniaX** [comment] 2023-05-01 12:47
new install. I only starting trying out pinecone yesterday. the code is just the boilerplate: https://github.com/PlutoniaX/pynecone-test after running pc init.
the webpage loads fine but just has that error message attached above which I can click away and it will hide at the bottom left corner.

**Comment by Lendemor** [comment] 2023-10-16 11:28
Closing this as it concerns an old version.
Feel free to reopen if it still occurs on latest version.

**Closed by Lendemor** 2023-10-16 11:28 UTC
Labels: needs investigation
