### ISSUE TITLE
Full control form components are not updating state

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#868] opened 2023-04-25 17:20 UTC
**Describe the bug**

Create a "full control" input; the state doesn't get updated.

**To Reproduce**

https://github.com/masenf/repro-full-control-broken

```python
class State(pc.State):
    v: str = ""
    slow: bool = False

    @pc.var
    def slow_v(self) -> str:
        if self.slow:
            time.sleep(0.5)
        return repr(self.v)


def index() -> pc.Component:
    return pc.center(
        pc.vstack(
            pc.heading(State.slow_v, font_size="2em"),
            pc.input(value=State.v, on_change=State.set_v),
            pc.hstack(pc.text("Slow?"), pc.checkbox(value=State.slow, on_change=State.set_slow)),
        ),
        padding_top="10%",
    )
```

**Expected behavior**
Expect that state value `v` is updated as user triggers `on_change` event.

** Specifics (please complete the following information):**
 - Python Version: python 3.11.2
 - Pynecone Version: `main`
 - OS: macOS 13.2.1
 - Browser (Optional): Safari, Chrome, Firefox
 
**Additional context**
Maybe duplicate of #817? Although that one states "works great, but throws a warning". In my experience, it doesn't work at all.

**Comment by masenf** [comment] 2023-04-25 17:23
@ElijahAhianyo @picklelo Consider holding the release of 0.1.25 until this is resolved. Running on `main` branch regresses functionality for all of my apps that are using the default `set_x` event handler with a fully controlled input.

I don't reproduce the issue with custom event handlers, even if all they do is assign the variable.

For example, with the following diff, my repro repo no longer repros this issue

```patch
diff --git a/repro_full_control_broken/repro_full_control_broken.py b/repro_full_control_broken/repro_full_control_broken.py
index 38dd402..bf2a355 100644
--- a/repro_full_control_broken/repro_full_control_broken.py
+++ b/repro_full_control_broken/repro_full_control_broken.py
@@ -16,6 +16,9 @@ class State(pc.State):
             time.sleep(0.5)
         return repr(self.v)
 
+    def set_v(self, v: str):
+        self.v = v
+
```

**Comment by picklelo** [comment] 2023-04-25 17:47
Got it, will hold off - I'll take a deeper look into what's happening here. We merged some PRs related to dynamic setters yesterday which may have affected this. Will add unit tests to catch this.

**Comment by masenf** [comment] 2023-04-25 18:48
I revert bd03e9290cb972b71d56e143ac44c63c22ab2b65 and the issue goes away. That's why I thought it was related to #700.

```console
git revert bd03e9290cb972b71d56e143ac44c63c22ab2b65
```

There's definitely still delay issues that break interactivity when the server is "slow". Those will need to be addressed by client-side state that doesn't block on server operations

**Comment by ElijahAhianyo** [comment] 2023-04-25 21:24
> I revert [bd03e92](https://github.com/pynecone-io/pynecone/commit/bd03e9290cb972b71d56e143ac44c63c22ab2b65) and the issue goes away. That's why I thought it was related to #700.
> 
> ```
> git revert bd03e9290cb972b71d56e143ac44c63c22ab2b65
> ```
> 
> There's definitely still delay issues that break interactivity when the server is "slow". Those will need to be addressed by client-side state that doesn't block on server operations

Ah right, that's correct. Took a quick glance at this and its related to #817. Definitely the cause for the console log errors. Will look into this

**Comment by Alek99** [comment] 2023-04-25 22:34
Taking a look now

**Comment by Alek99** [comment] 2023-04-26 01:08
I think we may have to rework how that pr is done, it seems to not work if you manually create a `set_v`. I may just revert these changes for now and we can rework it in the next release. One problem is the the `is_full_control` logic may need to be updated.

```python
import pynecone as pc
import time
class State(pc.State):
    v: str = ""
    slow: bool = False

    @pc.var
    def slow_v(self) -> str:
        if self.slow:
            time.sleep(0.5)
        return repr(self.v)
    
    def set_v(self, v: str):   
         self.v = v 

    # def set_slow(self, slow: bool):
    #     self.slow = slow 
 
def index() -> pc.Component:
    return pc.center( 
        pc.vstack(  
            pc.heading(State.slow_v, font_size="2em"),
            pc.input(value=State.v, on_change=State.set_v),
            pc.hstack(
                pc.text("Slow?"), 
                pc.checkbox(value=State.slow, on_change=State.set_slow)
            ),
        ),
        padding_top="10%",
    )
# App
app = pc.App(state=State)
app.add_page(index)
app.compile()
```
Going to investigate this more now and I'll put of a fix if possible otherwise will revert and we c an fix in next release.

**Closed** 2023-11-27 20:14 UTC
Labels: bug
