### ISSUE TITLE
[firefox] Unhandled Runtime Error: Should not already be working. after dismissing rx.window_alert

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#1363] opened 2023-07-18 20:51 UTC
**Describe the bug**
After the alert window pops up and is dismissed, the page immediately throws an error.

**To Reproduce**
```python
import reflex as rx


class State(rx.State):
    pass


def index() -> rx.Component:
    return rx.button(
        "Alert", on_click=rx.window_alert("Hello World!")
    )


app = rx.App(state=State)
app.add_page(index)
app.compile()
```

**Expected behavior**
Alert is dismissed without error

**Screenshots**
![image](https://github.com/reflex-dev/reflex/assets/1524005/f3133edb-8bd0-47d7-9e58-e66c21424b2a)

**Specifics (please complete the following information):**
 - Python Version: 3.11.4
 - Reflex Version: 0.2.1a1 (and also 0.2.0)
 - OS: macOS (and in docker container)
 - Browser (Optional): Firefox 115 (not repro in safari or chrome)
 
**Additional context**
Reproducible in dev mode, **does not seem to affect prod mode.**

**Comment by masenf** [comment] 2023-07-19 22:19
Related to https://github.com/facebook/react/issues/17355

Low priority, since not seen in prod mode.

**Comment by ElijahAhianyo** [comment] 2024-04-08 12:29
@masenf Was this fixed? I'm not able to reproduce this on main.

**Comment by picklelo** [comment] 2024-06-03 02:22
Closing this issue for now.

**Closed by picklelo** 2024-06-03 02:22 UTC
Labels: bug
