### ISSUE TITLE
Data_table responsive styling 

### ISSUE THREAD

**Issue by DPetuskey** [reflex-dev/reflex#133] opened 2022-12-18 05:40 UTC
**Describe the bug**
When the parent container of a data_table has responsive widths, the data_table doesn't adjust properly.

**To Reproduce**

```python

pc.center(
                pc.vstack(
                    pc.heading("Saved Q&A", font_size="1.5em"),
                    pc.divider(),
                    pc.data_table(
                        data=State.questions,
                        columns=["Prompt", "Answer"],
                        pagination = True,
                        search = True,
                        sort = True,
                        width="100%",
                    ),
                    shadow="lg",
                    padding="1em",
                    border_radius="lg",
                    width="100%",
                ),
                width=["100%", "100%", "75%", "50%", "50%"],
            ),

```

**Expected behavior**
Expect the data_table to mirror the scaling of the parent. 

**Screenshots**
![Screen Shot 2022-12-17 at 9 39 13 PM](https://user-images.githubusercontent.com/98362056/208283283-36c4de50-fea7-462e-9507-2cd42f4d6126.png)

** Specifics (please complete the following information):**
 - Python Version:  3.11
 - Pynecone Version: 0.1.10
 - OS: Mac
 - Browser (Optional):
 
**Additional context**

**Comment by Alek99** [comment] 2022-12-18 05:43
Got it looking into this

**Comment by rahulbagai** [comment] 2023-07-19 21:47
@Alek99 @DPetuskey Hello, I wanted to check if this problem is still persisting because I haven't been able to reproduce it on my end.

**Details**
- Python version: 3.11.4
- Reflex version: current reflex code as of today
- OS: local Docker container `cat /etc/os-release  PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"`
- Browser - Chrome Version 114.0.5735.198

Here my code: https://paste.ofcode.org/KTqGAiDwDH545YVyhFCp96

<img width="833" alt="screenshot_0012" src="https://github.com/reflex-dev/reflex/assets/20045757/156bc944-3f33-45ad-9382-858c14a9c861">

**Comment by rahulbagai** [comment] 2023-07-19 21:47
@Alek99 @DPetuskey Hello, I wanted to check if this problem is still persisting because I haven't been able to reproduce it on my end.

**Details**
- Python version: 3.11.4
- Reflex version: current reflex code as of today
- OS: `cat /etc/os-release  PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"`
- Browser - Chrome Version 114.0.5735.198

Here my code.: https://paste.ofcode.org/KTqGAiDwDH545YVyhFCp96

<img width="833" alt="screenshot_0012" src="https://github.com/reflex-dev/reflex/assets/20045757/156bc944-3f33-45ad-9382-858c14a9c861">

**Comment by ElijahAhianyo** [comment] 2023-08-18 09:53
can confirm this works as expected. Closing this issue now

**Closed by ElijahAhianyo** 2023-08-18 09:53 UTC
Labels: bug
