### ISSUE TITLE
add toggleColorMode support for Recharts charts

### ISSUE THREAD

**Issue by Lendemor** [reflex-dev/reflex#412] opened 2023-01-31 15:06 UTC
**Describe the bug**
When using a `pc.chart`, if you use the ` toggleColorMode()` method to switch to dark mode, the lines and labels of the charts do not change color.

**To Reproduce**
Add a button to toggle color mode and any chart. 

**Expected behavior**
Chart labels can be used in DarkMode

**Screenshots**

Labels did not change colors when toggling dark mode: 
![image](https://user-images.githubusercontent.com/4015177/215796652-e873b576-06b6-4a7c-b110-70d18ffd8041.png)

** Specifics (please complete the following information):**
 - Python Version: 3.8.10
 - Pynecone Version: 0.1.14
 - OS: Ubuntu 20.04

**Comment by Alek99** [comment] 2023-02-01 05:26
Yeah dark/light toggling only works with chakra because its a chakra feature we can work on trying to integrate this with the other libs pynecone wraps

**Comment by Alek99** [comment] 2023-02-01 05:27
Marking as enhancement because its expected behaviors as of now

**Closed** 2024-03-26 11:47 UTC
Labels: enhancement
