### ISSUE TITLE
[REF-2027] rx.color should accept "accent" as a valid color

### ISSUE THREAD

**Issue by masenf** [reflex-dev/reflex#2674] opened 2024-02-20 15:30 UTC
**Describe the bug**
No easy way to reference a shade of the primary theme accent_color without resorting to CSS var str literal like `var(--accent-10)`

**To Reproduce**
```python
import reflex as rx

rx.color("accent", 10)
```

```console
ValueError: prop value for color of the `color` component should be one of the following: 'gray','mauve','slate','sage','olive','sand','tomato','red','ruby','crimson','pink','plum','purple','violet','iris','indigo','blue','cyan','teal','jade','green','grass','brown','orange','sky','mint','lime','yellow','amber','gold','bronze'. Got 'accent' instead
```

<sub>[REF-2027](https://linear.app/reflex-dev/issue/REF-2027/rxcolor-should-accept-accept-as-a-valid-color)</sub>

**Comment by wassafshahzad** [comment] 2024-02-20 19:35
Please assign it to me

**Comment by masenf** [comment] 2024-02-20 19:36
picked up by OSS contributor wassafshahzad

**Comment by wassafshahzad** [comment] 2024-02-20 19:51
> OSS

In the title did you mean accent ?

**Comment by masenf** [comment] 2024-02-20 19:54
> In the title did you mean accent ?

yes 100% 😊. The generic name for the theme `accent_color` is `accent`.

**Comment by Yummy-Yums** [comment] 2024-02-22 19:34
hey guys sorry i thought this was dormant or something, dropped the PR. The assignee can go ahead

**Comment by wassafshahzad** [comment] 2024-02-22 19:44
@Yummy-Yums You can take the issue since your already have a PR up. I can take another issue

**Comment by Yummy-Yums** [comment] 2024-02-22 20:06
> @Yummy-Yums You can take the issue since your already have a PR up. I can take another issue

oh no, it's not cool..I'm already working on another issue as well..unexpected behaviour of a button so I'm investigating

https://github.com/reflex-dev/reflex-web/pull/497

**Closed** 2024-02-26 03:47 UTC
