### ISSUE TITLE
Integer formatting foreach bug

### ISSUE THREAD

**Issue by jpbaltazar** [reflex-dev/reflex#1746] opened 2023-09-04 13:03 UTC
Calling a function through `rx.foreach` that formats decimal point does not work:

Result:

> 2

> 2.0

Expected

> 2.0

> 2.0

Minimal example to reproduce:

```python
import reflex as rx

class State(rx.State):
    pass


entries: list[int] = [
    2,
]

def display_entry(entry: int) -> rx.Component:
    return rx.tr(
        rx.td(f"{entry:.2f}"),
    )

def index() -> rx.Component:
    return rx.fragment(
        rx.table(
            rx.tbody(
                rx.foreach(
                    entries,
                    display_entry,
                ),
                rx.tr(
                    rx.td(
                        f"{2:.2f}",
                    ),
                )
            )
        )
    )


# Add state and page to the app.
app = rx.App()
app.add_page(index)
app.compile()

```

**Comment by masenf** [comment] 2023-09-04 21:52
@picklelo  this is going to be a fun one to fix... might have to just reimplement python formatting mini language in javascript 😬

**Comment by masenf** [comment] 2023-11-28 04:32
dupe of #2148

**Closed by masenf** 2023-11-28 04:32 UTC
Labels: bug, linear
