### ISSUE TITLE
[REF-3448] 404 not rendering

### ISSUE THREAD

**Issue by charlestondance** [reflex-dev/reflex#3720] opened 2024-07-30 15:56 UTC
**Describe the bug**
entering a random url give a 404 with text in the page
going to localhost:3000/404 updates the title but nothing is rendered in the page. Making a custom 404 has the same issue where no components are rendered in the page

**To Reproduce**
 - enter URL as above

**Expected behavior**
correct 404 page be returned at localhost:3000/404 

**Screenshots**

**Specifics (please complete the following information):**
 - Python Version:
 - Reflex Version:
 - OS: 
 - Browser (Optional):
 
**Additional context**

<sub>[REF-3448](https://linear.app/reflex-dev/issue/REF-3448/404-not-rendering)</sub>

**Comment by masenf** [comment] 2024-07-30 16:39
I'm able to reproduce the issue, even with our main website https://reflex.dev/404/ renders as a blank page.

Not sure what the problem is.

Is there a use case? Or are you just wondering for consistency sake why `/404` doesn't render? (I'm also curious)

**Comment by Lendemor** [comment] 2024-07-30 17:12
If only for consistency we should figure out what happens and fix it I think.

**Comment by charlestondance** [comment] 2024-07-30 17:36
No probs. My two use cases are:

1) Custom 404. You cant make a custom 404 now as no components will be rendered
2) I am using chakra.box as an iframe so i don't see the title change. All i can see in the iframe is blank space and i have no idea what is going on.

**Comment by masenf** [comment] 2024-07-30 17:57
> Custom 404

does it not work when you use `app.add_custom_404_page`? reflex.dev uses custom 404 and it seems to work fine (although accessing it directly via `/404` does not work)

**Comment by charlestondance** [comment] 2024-07-30 19:27
Custom or built in 404s do not render at /404. I am trying to handle and return /404 under certain cases that i check for. Automatically returning 404 on random routes doesnt help my use case.

**Comment by charlestondance** [comment] 2024-07-31 06:21
Problems with dynamic routes return the broken /404 automatically as well.

**Comment by Manas1820** [comment] 2024-07-31 07:32
@charlestondance can you share a small example snippet ? Just want to test if its fixed with the mentioned PR !

**Comment by Manas1820** [comment] 2024-07-31 07:51
```python3
"""Welcome to Reflex! This file outlines the steps to create a basic app."""

import reflex as rx

from rxconfig import config


class State(rx.State):
    """The app state."""

    @rx.var
    def test_id(self) -> str:
        return self.router.page.params.get("id", "No Test ID")


@rx.page(route="/test/[id]")
def test():
    """A page that updates based on the route."""
    return rx.container(
        rx.heading(f"Testing ID: {State.test_id}", size="9"),
        spacing="5",
        align="center",
        justify="center",
        min_height="85vh",
    )


app = rx.App()
app.add_custom_404_page(
    rx.container(
        rx.color_mode.button(position="top-right"),
        rx.vstack(
            rx.heading("Oops! Page Not Found", size="9"),
            rx.text(
                "It looks like the page you're looking for doesn't exist. You can start exploring by editing ",
                rx.code(f"{config.app_name}/{config.app_name}.py"),
                size="5",
            ),
            rx.link(
                rx.button("Visit our Documentation"),
                href="https://reflex.dev/docs/getting-started/introduction/",
                is_external=True,
            ),
            spacing="5",
            justify="center",
            min_height="85vh",
        ),
        rx.logo(),
    )
)
```

I have verified my code using an example, as shown in the screenshots after the updated code mentioned in my [PR](https://github.com/reflex-dev/reflex/pull/3723).

<img width="1438" alt="image" src="https://github.com/user-attachments/assets/e52dc118-8698-4443-86f2-91d70daa3489">

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/57380fdc-9dae-4752-8aae-6d7b5897368c">

@charlestondance Can you confirm once if this is the expected outcome !

**Comment by picklelo** [comment] 2024-11-02 00:57
This should be resolved in the latest code (please re-open if needed!)

**Closed by picklelo** 2024-11-02 00:57 UTC
Labels: bug, linear, hacktoberfest
