### ISSUE TITLE
hope to support toast component

### ISSUE THREAD

**Issue by ltm920716** [reflex-dev/reflex#1900] opened 2023-10-02 06:22 UTC
**Describe the bug**
Sorry for here again，this not a bug，the toast component can not be warped like other react library，could reflex support toast？

**To Reproduce**
```
from __future__ import annotations
from typing import Any, Union

from reflex.components.libs.chakra import ChakraComponent
from reflex.vars import Var


class ToastWindow(ChakraComponent):
    tag = 'useToast'

    position = Var[str]

    duration = Var[int]

    is_closable = Var[bool]

    status = Var[str]

    def get_event_triggers(self) -> dict[str, Union[Var, Any]]:
        return {
            **super().get_event_triggers(),
            "on_close": lambda: [],
            "on_open": lambda: []
        }
    
use_toast = ToastWindow().create
```

**Expected behavior**
could reflex support toast？

**Comment by iron3oxide** [comment] 2023-10-02 16:54
this seems to be a duplicate of #358

**Closed** 2023-10-02 16:59 UTC
