### ISSUE TITLE
pc.upload does not support event handler list

### ISSUE THREAD

**Issue by evandeng2009** [reflex-dev/reflex#1297] opened 2023-07-03 14:53 UTC
**Describe the bug**
pc.uolpad, followed by pc.icon:
`pc.icon(tag="arrow_up", on_click=[lambda: State.assign_tid(item[1][1]), lambda: State.handle_upload(pc.upload_files())]`
And handle_upload will read  a base var setted by assign_tid to rename the file.

Problem is: I see assign_tid has been executed, while handle_upload not. If this is not supported, anyway to rename the uploaded file with a dymanic and specified one?

**To Reproduce**
 - Code/Link to Repo:

**Expected behavior**

**Screenshots**

** Specifics (please complete the following information):**
 - Python Version:3.7
 - Reflex Version:0.1.34
 - OS: Windows
 - Browser (Optional):
 
**Additional context**

**Comment by milochen0418** [comment] 2023-07-03 16:43
Yes, the `pc.upload_files()` cannot work in the event chain.

**Comment by evandeng2009** [comment] 2023-07-31 14:38
I need to rename the file according to the place where upload button is clicked. Anyone knows how to do this as a workaround before event chain finally is supported please?

**Comment by masenf** [comment] 2023-11-27 22:59
Dupe of #1066

**Closed by masenf** 2023-11-27 22:59 UTC
Labels: bug
